name: easygo-training-em

channels:
    - conda-forge
    - defaults

dependencies:
    - emg3d
    - empymod
    - matplotlib
    - discretize
    - h5py
    - scooby
    - jupyter
    - tqdm
    - pooch
    - xarray
    - ipympl
    - ipykernel
    - jupyterlab
